extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_dl_room02_geo[];
extern const GeoLayout rr_dl_room03_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const u8 rr_area_1_collision_rooms[];
extern const MacroObject rr_area_1_macro_objs[];
extern Lights1 rr_dl_clouds_layer5_area1_lights;
extern Lights1 rr_dl_deathplane_lights;
extern Lights1 rr_dl_stone_layer1_area1_lights;
extern Lights1 rr_dl_vines01_lights;
extern Lights1 rr_dl_vines02_lights;
extern u8 rr_dl_clouds_ia4[];
extern u8 rr_dl_bob_textures_04800_rgba16_ci8[];
extern u8 rr_dl_bob_textures_04800_rgba16_ci8_pal_rgba16[];
extern u8 rr_dl_vines01_ci8[];
extern u8 rr_dl_vines01_ci8_pal_rgba16[];
extern u8 rr_dl_vines02_ci8[];
extern u8 rr_dl_vines02_ci8_pal_rgba16[];
extern Vtx rr_dl_clouds_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_clouds_mesh_layer_5_tri_0[];
extern Vtx rr_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx rr_dl_temple_mesh_layer_1_vtx_0[713];
extern Gfx rr_dl_temple_mesh_layer_1_tri_0[];
extern Vtx rr_dl_vines_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_001_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_001_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_002_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_002_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_003_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_003_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_004_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_004_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_005_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_005_mesh_layer_5_tri_0[];
extern Vtx rr_dl_vines_006_mesh_layer_5_vtx_0[4];
extern Gfx rr_dl_vines_006_mesh_layer_5_tri_0[];
extern Gfx mat_rr_dl_clouds_layer5_area1[];
extern Gfx mat_revert_rr_dl_clouds_layer5_area1[];
extern Gfx mat_rr_dl_deathplane[];
extern Gfx mat_rr_dl_stone_layer1_area1[];
extern Gfx mat_revert_rr_dl_stone_layer1_area1[];
extern Gfx mat_rr_dl_vines01[];
extern Gfx mat_revert_rr_dl_vines01[];
extern Gfx mat_rr_dl_vines02[];
extern Gfx mat_revert_rr_dl_vines02[];
extern Gfx rr_dl_clouds_mesh_layer_5[];
extern Gfx rr_dl_deathplane_mesh_layer_5[];
extern Gfx rr_dl_temple_mesh_layer_1[];
extern Gfx rr_dl_vines_mesh_layer_5[];
extern Gfx rr_dl_vines_001_mesh_layer_5[];
extern Gfx rr_dl_vines_002_mesh_layer_5[];
extern Gfx rr_dl_vines_003_mesh_layer_5[];
extern Gfx rr_dl_vines_004_mesh_layer_5[];
extern Gfx rr_dl_vines_005_mesh_layer_5[];
extern Gfx rr_dl_vines_006_mesh_layer_5[];
extern Gfx rr_dl_material_revert_render_settings[];
