extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const MacroObject rr_area_1_macro_objs[];
extern Lights1 rr_dl_floor_lights;
extern Lights1 rr_dl_walls_lights;
extern u8 rr_dl_castle_grounds_textures_01000_rgba16_ci8[];
extern u8 rr_dl_castle_grounds_textures_01000_rgba16_ci8_pal_rgba16[];
extern Vtx rr_dl_floor_mesh_layer_1_vtx_0[4];
extern Gfx rr_dl_floor_mesh_layer_1_tri_0[];
extern Vtx rr_dl_walls_mesh_layer_1_vtx_0[60];
extern Gfx rr_dl_walls_mesh_layer_1_tri_0[];
extern Gfx mat_rr_dl_floor[];
extern Gfx mat_rr_dl_walls[];
extern Gfx mat_revert_rr_dl_walls[];
extern Gfx rr_dl_floor_mesh_layer_1[];
extern Gfx rr_dl_walls_mesh_layer_1[];
extern Gfx rr_dl_material_revert_render_settings[];
