extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_trans_001_lights;
extern Lights1 castle_grounds_dl_grass_001_lights;
extern Lights1 castle_grounds_dl_dirt_lights;
extern Lights1 castle_grounds_dl_warp_001_lights;
extern u8 castle_grounds_dl_bob_textures_05800_rgba16_ci8[];
extern u8 castle_grounds_dl_bob_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_bob_textures_09000_rgba16_ci8[];
extern u8 castle_grounds_dl_bob_textures_09000_rgba16_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_ground_mesh_layer_1_vtx_0[319];
extern Gfx castle_grounds_dl_ground_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_ground_mesh_layer_1_vtx_1[200];
extern Gfx castle_grounds_dl_ground_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_0[84];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_1[186];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_warpplane02_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_warpplane02_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_trans_001[];
extern Gfx mat_castle_grounds_dl_grass_001[];
extern Gfx mat_revert_castle_grounds_dl_grass_001[];
extern Gfx mat_castle_grounds_dl_dirt[];
extern Gfx mat_revert_castle_grounds_dl_dirt[];
extern Gfx mat_castle_grounds_dl_warp_001[];
extern Gfx castle_grounds_dl_deathplane_mesh_layer_5[];
extern Gfx castle_grounds_dl_ground_mesh_layer_1[];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1[];
extern Gfx castle_grounds_dl_warpplane02_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
