extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_trans_lights;
extern Lights1 bob_dl_ground_lights;
extern Lights1 bob_dl_dirt_lights;
extern Lights1 bob_dl_warp_lights;
extern u8 bob_dl_bob_textures_05800_rgba16_ci8[];
extern u8 bob_dl_bob_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_bob_textures_09000_rgba16_ci8[];
extern u8 bob_dl_bob_textures_09000_rgba16_ci8_pal_rgba16[];
extern Vtx bob_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_ground_mesh_layer_1_vtx_0[319];
extern Gfx bob_dl_ground_mesh_layer_1_tri_0[];
extern Vtx bob_dl_ground_mesh_layer_1_vtx_1[200];
extern Gfx bob_dl_ground_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Ground_mesh_layer_1_vtx_0[87];
extern Gfx bob_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Ground_mesh_layer_1_vtx_1[184];
extern Gfx bob_dl_Ground_mesh_layer_1_tri_1[];
extern Vtx bob_dl_warpplane02_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_warpplane02_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_trans[];
extern Gfx mat_bob_dl_ground[];
extern Gfx mat_revert_bob_dl_ground[];
extern Gfx mat_bob_dl_dirt[];
extern Gfx mat_revert_bob_dl_dirt[];
extern Gfx mat_bob_dl_warp[];
extern Gfx bob_dl_deathplane_mesh_layer_5[];
extern Gfx bob_dl_ground_mesh_layer_1[];
extern Gfx bob_dl_Ground_mesh_layer_1[];
extern Gfx bob_dl_warpplane02_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
