extern const GeoLayout cotmc_area_1_geo[];
extern const GeoLayout cotmc_area_1[];
extern const Collision cotmc_area_1_collision[];
extern const MacroObject cotmc_area_1_macro_objs[];
extern Lights1 cotmc_dl_trans_001_lights;
extern Lights1 cotmc_dl_f3dlite_material_lights;
extern Lights1 cotmc_dl_warp_001_lights;
extern Vtx cotmc_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx cotmc_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx cotmc_dl_ground_mesh_layer_1_vtx_0[496];
extern Gfx cotmc_dl_ground_mesh_layer_1_tri_0[];
extern Vtx cotmc_dl_Ground_mesh_layer_1_vtx_0[266];
extern Gfx cotmc_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx cotmc_dl_warpplane02_mesh_layer_1_vtx_0[4];
extern Gfx cotmc_dl_warpplane02_mesh_layer_1_tri_0[];
extern Gfx mat_cotmc_dl_trans_001[];
extern Gfx mat_cotmc_dl_f3dlite_material[];
extern Gfx mat_cotmc_dl_warp_001[];
extern Gfx cotmc_dl_deathplane_mesh_layer_5[];
extern Gfx cotmc_dl_ground_mesh_layer_1[];
extern Gfx cotmc_dl_Ground_mesh_layer_1[];
extern Gfx cotmc_dl_warpplane02_mesh_layer_1[];
extern Gfx cotmc_dl_material_revert_render_settings[];
