extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_trans_001_lights;
extern Lights1 jrb_dl_f3dlite_material_lights;
extern Lights1 jrb_dl_warp_001_lights;
extern Vtx jrb_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx jrb_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_ground_mesh_layer_1_vtx_0[496];
extern Gfx jrb_dl_ground_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_0[266];
extern Gfx jrb_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_warpplane02_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_warpplane02_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_trans_001[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_jrb_dl_warp_001[];
extern Gfx jrb_dl_deathplane_mesh_layer_5[];
extern Gfx jrb_dl_ground_mesh_layer_1[];
extern Gfx jrb_dl_Ground_mesh_layer_1[];
extern Gfx jrb_dl_warpplane02_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
