extern const GeoLayout ttc_area_1_geo[];
extern const GeoLayout ttc_area_1[];
extern const Collision ttc_area_1_collision[];
extern const MacroObject ttc_area_1_macro_objs[];
extern Lights1 ttc_dl_floor_lights;
extern Lights1 ttc_dl_bark_001_lights;
extern Lights1 ttc_dl_leaves_001_lights;
extern Lights1 ttc_dl_picture_lights;
extern Lights0 ttc_dl_stairs_lights;
extern Lights1 ttc_dl_walls_lights;
extern u8 ttc_dl_bark_ci8[];
extern u8 ttc_dl_bark_ci8_pal_rgba16[];
extern u8 ttc_dl_leaves_ci8[];
extern u8 ttc_dl_leaves_ci8_pal_rgba16[];
extern u8 ttc_dl_squidward32_ci8[];
extern u8 ttc_dl_squidward32_ci8_pal_rgba16[];
extern u8 ttc_dl_castle_grounds_textures_01000_rgba16_ci8[];
extern u8 ttc_dl_castle_grounds_textures_01000_rgba16_ci8_pal_rgba16[];
extern Vtx ttc_dl_floor_mesh_layer_1_vtx_0[15];
extern Gfx ttc_dl_floor_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_large_tree_mesh_layer_1_vtx_0[483];
extern Gfx ttc_dl_large_tree_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_large_tree_mesh_layer_1_vtx_1[618];
extern Gfx ttc_dl_large_tree_mesh_layer_1_tri_1[];
extern Vtx ttc_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx ttc_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_stairs_mesh_layer_1_vtx_0[4132];
extern Gfx ttc_dl_stairs_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_walls_mesh_layer_1_vtx_0[60];
extern Gfx ttc_dl_walls_mesh_layer_1_tri_0[];
extern Gfx mat_ttc_dl_floor[];
extern Gfx mat_ttc_dl_bark_001[];
extern Gfx mat_revert_ttc_dl_bark_001[];
extern Gfx mat_ttc_dl_leaves_001[];
extern Gfx mat_revert_ttc_dl_leaves_001[];
extern Gfx mat_ttc_dl_picture[];
extern Gfx mat_revert_ttc_dl_picture[];
extern Gfx mat_ttc_dl_stairs[];
extern Gfx mat_ttc_dl_walls[];
extern Gfx mat_revert_ttc_dl_walls[];
extern Gfx ttc_dl_floor_mesh_layer_1[];
extern Gfx ttc_dl_large_tree_mesh_layer_1[];
extern Gfx ttc_dl_Plane_mesh_layer_1[];
extern Gfx ttc_dl_stairs_mesh_layer_1[];
extern Gfx ttc_dl_walls_mesh_layer_1[];
extern Gfx ttc_dl_material_revert_render_settings[];
